engines:
 duplication:
   enabled: true
   checks:
     Similar code:
       enabled: false
   config:
     languages:
     - javascript
 fixme:
   enabled: true
ratings:
 paths:
 - "server/*.js"
 - "server/**/*.js"
exclude_paths:
- "node_modules/"
- "server/test/"
- "client/__test__/*"
- "client/test/*"
- "bundle.js"
- "dist/"
- "coverage/"
- "reports"
- ".nyc_output/"
- "client/public/js/bundle.js"
-