export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGGEDIN_USER = 'LOGGEDIN_USER';
export const LOGOUT_USER = 'LOGGEDOUT_USER';
export const CREATE_IDEA = 'CREATE_IDEA';
export const LIST_PUBLIC_IDEAS = 'LIST_PUBLIC_IDEAS';
